- name: Deploy ArgoCD on EKS
  hosts: localhost
  vars:
    ns: "argocd"
  tasks:
    - name: Create ArgoCD Application
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ecomm-ci-cd
            namespace: "{{ ns }}"
            annotations:
              argocd-image-updater.argoproj.io/image-list: |
                backend=314146337686.dkr.ecr.us-east-1.amazonaws.com/ecomm.ci.cd.back,
                frontend=314146337686.dkr.ecr.us-east-1.amazonaws.com/ecomm.ci.cd.front
              argocd-image-updater.argoproj.io/backend.update-strategy: latest
              argocd-image-updater.argoproj.io/frontend.update-strategy: latest
              argocd-image-updater.argoproj.io/write-back-method: git
          spec:
            project: default
            source:
              repoURL: "https://github.com/abdessamadabidar/GitOps.git"
              targetRevision: HEAD
              path: ecomm-ci-cd
            destination:
              server: "https://kubernetes.default.svc"
              namespace: default
            syncPolicy:
              automated:
                selfHeal: true
                prune: true
    